services:
  postgres:
    image: postgres:18.3
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PANTRY_PAL_DB=${POSTGRES_DB}
      - PANTRY_PAL_USER=${PANTRY_PAL_USER}
      - PANTRY_PAL_USER_PASSWORD=${PANTRY_PAL_USER_PASSWORD}
      - PANTRY_PAL_SCHEMA=${PANTRY_PAL_SCHEMA}
      - KEYCLOAK_DB=${KEYCLOAK_DB}
      - KEYCLOAK_ADMIN=${KEYCLOAK_DB_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_DB_ADMIN_PASSWORD}
      - KEYCLOAK_USER=${KEYCLOAK_DB_USER}
      - KEYCLOAK_USER_PASSWORD=${KEYCLOAK_DB_USER_PASSWORD}
      - KEYCLOAK_SCHEMAS=${KEYCLOAK_DB_SCHEMA}
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pantrypal-pgdata:/var/lib/postgresql/data
    hostname: pantrypaldb
    container_name: pantry_pal_db
    restart: unless-stopped
    networks:
      - pantrypal_network
      - pantrypal_keycloak_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4:9.14.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pantrypal-pgadmin-data:/var/lib/pgadmin
    container_name: pantry_pal_pgadmin
    hostname: pantrypalpgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - pantrypal_network

  keycloak:
    image: keycloak/keycloak:26.6
    container_name: pantry_pal_keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=pantrypaldb
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=${KEYCLOAK_DB}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_USER_PASSWORD}
      - KC_DB_SCHEMA=${KEYCLOAK_DB_SCHEMA}
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: [ "start-dev", "--import-realm", "--http-port", "8080" ]
    ports:
      - "18080:8080"
      - "7443:7443"
    volumes:
      - pantrypal-keycloak-data:/opt/keycloak/data
      - ./pantrypal-realm.json:/opt/keycloak/data/import/realm.json
    restart: always
    networks:
      - pantrypal_keycloak_network

  pantrypal:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: pantry_pal
    hostname: pantrypal
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - POSTGRES_USER=${PANTRY_PAL_USER}
      - POSTGRES_PASSWORD=${PANTRY_PAL_USER_PASSWORD}
      - PANTRY_PAL_SCHEMA=${PANTRY_PAL_SCHEMA}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_EXTERNAL_BASE_URL=${KEYCLOAK_EXTERNAL_BASE_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_AUDIENCE=${KEYCLOAK_AUDIENCE}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - IMAGES_PATH=/app/pantrypal/
    volumes:
      - images-data:/app/pantrypal/
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - pantrypal_network
      - pantrypal_keycloak_network

volumes:
  pantrypal-pgdata:
  pantrypal-pgadmin-data:
  pantrypal-keycloak-data:
    driver: local
  images-data:
    driver: local

networks:
  pantrypal_network:
    external: false
  pantrypal_keycloak_network:
    driver: bridge
