services:
  pantrypal:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: pantry_pal
    hostname: pantrypal
    ports:
      - "8080:8080"
    env_file:
      - ./deploy/envfiles/pantrypal.env
    volumes:
      - images-data:/app/pantrypal/
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      mongodb:
        condition: service_started
    networks:
      - application_network
      - keycloak_network

  pantrypal-migration:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: pantry_pal_migration
    env_file:
      - ./deploy/envfiles/pantrypal.env
    environment:
      - GENERATE_MIGRATION=true
      - MIGRATIONS_PATH=/app/migrations
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application_network
    profiles:
      - migration

  pantrypal-db-init:
    build:
      context: ./database
      dockerfile: Dockerfile.init
    env_file:
      - ../../deploy/envfiles/postgres-common.env
      - ./deploy/envfiles/postgres.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application_network
    profiles:
      - db-init
    secrets:
      - postgres_password
      - pantrypal_admin_password
      - pantrypal_user_password

  pantrypal-mongo-init:
    image: mongodb/mongodb-community-server:8.3.2-ubuntu2204-slim
    restart: no
    env_file:
      - ../../deploy/envfiles/mongodb-common.env
      - ./deploy/envfiles/mongodb.env
    volumes:
      - ./database/mongodb/01-create-pantrypal-mongo-user.sh:/mongo-init.sh:ro
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - /mongo-init.sh
    networks:
      - application_network
    profiles:
      - mongo-init
    secrets:
      - mongodb_root_password
      - mongodb_pantrypal_password

  pantrypal-kc-import:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.import
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - keycloak_network
    profiles:
      - kc-import

volumes:
  images-data:
    driver: local

networks:
  application_network:
    external: true
  keycloak_network:
    external: true

secrets:
  postgres_password:
    file: ./deploy/secrets/postgres_password.txt
  pantrypal_admin_password:
    file: ./deploy/secrets/pantrypal_admin_password.txt
  pantrypal_user_password:
    file: ./deploy/secrets/pantrypal_user_password.txt
  mongodb_root_password:
    file: ./deploy/secrets/mongodb_root_password.txt
  mongodb_pantrypal_password:
    file: ./deploy/secrets/mongodb_pantrypal_password.txt
