services:
  pantrypal:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: pantry_pal
    hostname: pantrypal
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - POSTGRES_USER=${PANTRY_PAL_USER}
      - POSTGRES_PASSWORD=${PANTRY_PAL_USER_PASSWORD}
      - PANTRY_PAL_SCHEMA=${PANTRY_PAL_SCHEMA}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_EXTERNAL_BASE_URL=${KEYCLOAK_EXTERNAL_BASE_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_AUDIENCE=${KEYCLOAK_AUDIENCE}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - IMAGES_PATH=/app/pantrypal/
      - MONGODB_URI=${MONGODB_CONNECTION_STRING}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - images-data:/app/pantrypal/
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      mongodb:
        condition: service_started
    networks:
      - application_network
      - keycloak_network

  pantrypal-migration:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: pantry_pal_migration
    environment:
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - POSTGRES_USER=${PANTRY_PAL_USER}
      - POSTGRES_PASSWORD=${PANTRY_PAL_USER_PASSWORD}
      - PANTRY_PAL_SCHEMA=${PANTRY_PAL_SCHEMA}
      - GENERATE_MIGRATION=true
      - MIGRATIONS_PATH=/app/migrations
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_EXTERNAL_BASE_URL=${KEYCLOAK_EXTERNAL_BASE_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_AUDIENCE=${KEYCLOAK_AUDIENCE}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application_network
    profiles:
      - migration

  pantrypal-db-init:
    build:
      context: ./database
      dockerfile: Dockerfile.init
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_DB=${KEYCLOAK_DB}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_USER_PASSWORD=${KEYCLOAK_USER_PASSWORD}
      - KEYCLOAK_SCHEMAS=${KEYCLOAK_SCHEMAS}
      - PANTRY_PAL_DB=${PANTRY_PAL_DB}
      - PANTRY_PAL_USER=${PANTRY_PAL_USER}
      - PANTRY_PAL_USER_PASSWORD=${PANTRY_PAL_USER_PASSWORD}
      - PANTRY_PAL_SCHEMA=${PANTRY_PAL_SCHEMA}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application_network
    profiles:
      - db-init

  pantrypal-kc-import:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.import
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - keycloak_network
    profiles:
      - kc-import

volumes:
  images-data:
    driver: local

networks:
  application_network:
    external: false
  keycloak_network:
